Run Time Evolution = 1

Create Output = 0

Use new FP method = 1

Add Stimulated Effects = 0

ystart = 1.0e-6

yend = 1.0e+1

Number of y steps = 400

Injection frequency = 10.0

Relative width of injection profile = 0.04

Minimum value of x = 1.0e-02

Maximum value of x = 100.0

Length of x array = 1500

#Electron temperature in K = 1.0e+08 // Need to decide whether to put Te or theta
Electron temperature in mec^2 = 0.1 // Need to decide whether to put Te or theta

Show GRACE movie = 1

Number of steps in the movie =  1

Output directory = ./outputs/

Verbosity = 1

